### ISSUE TITLE
gh-pages branch deployment

### ISSUE THREAD

**Issue by shadowlightwolf89** [avillafiorita/jekyll-rakefile#5]
How would I use this to deploy to a gh-pages branch? like, how do I specify that it needs to deploy to a branch?

I've been looking through the code, and it doesn't look like it's set up for gh-pages...

**Comment by avillafiorita** [comment]
Hi -
I have added an experimental (= I did not test it) task to deploy to github_pages. Invoke it with @rake deploy_github@ (I have also updated the documentation)

let me know what you think (and if it works).
